### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by openainext** [devfacet/natsboard#17]
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:607:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:607:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:607:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by devfacet** [comment]
Can you share your runtime environment information?

**Comment by sergiOO7** [comment]
I'm getting the same error
Windows 10

**Comment by pedia** [comment]
> { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:162:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
> 

me too. 
natsd running on centos7, natsboard running on mac os
and cause 200+ TIME_WAIT tcp6 socket on centos7.
